### ISSUE TITLE
How to temp disable module?

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#200]
Hi there,

WHMCS need to disable all 3rd party addons to debug an issue. 

However, on moving SSLCENTERWHMCS out of modules/addons WHMCS then throws an error:

```
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the WHMCS TroubleShooting Guide »

Error: Class 'MGModule\SSLCENTERWHMCS\mgLibs\process\AbstractMainDriver' not found in /home/whmcs/public_html/modules/servers/SSLCENTERWHMCS/Server.php:12
Stack trace:
#0 /home/whmcs/public_html/modules/servers/SSLCENTERWHMCS/Loader.php(117): require_once()
#1 [internal function]: MGModule\SSLCENTERWHMCS\Loader::loader('Server')
#2 /home/whmcs/public_html/modules/servers/SSLCENTERWHMCS/SSLCENTERWHMCS.php(7): spl_autoload_call('MGModule\\SSLCEN...')
#3 /home/whmcs/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): unknown()
#4 /home/whmcs/public_html/staff/modulequeue.php(0): WHMCS\Module\AbstractModule->load('SSLCENTERWHMCS')
#5 {main}
```

How can we temporarily disable the addon without losing any data or breaking WHMCS? 

Thanks,
C

**Comment by vlad-evg** [comment]
We will check shortly

**Comment by vlad-evg** [comment]
We are not able to recreate the issue. Please provide us FTP/SSH access via Ticket
